name: Tempo
channels:
- conda-forge
- defaults
- pytorch
dependencies:
- python=3.11
- sqlite=3.45.3
- discord.py=2.3.0
- numpy=2.0.0
- python-dotenv=1.0.1
- aiohttp=3.9.5
- tqdm=4.66.4
- ipython=8.26.0
- pysoundfile=0.12.1
- pytorch=2.3.1
- pillow=10.4.0
- spotipy=2.23.0
- pip=24.0
- pip:
  - "--editable=git+https://github.com/imayhaveborkedit/discord-ext-voice-recv#egg=discord-ext-voice-recv"
  - "git+https://github.com/kokarare1212/librespot-python"
  - "faster-whisper"
  - "wave"
  - "matcha-tts"